FROM debian:jessie
MAINTAINER Ian Philpot "ian.philpot@microsoft.com"

RUN apt-get update && apt-get install -y tar \
                                         git \
                                         curl \
                                         nano \
                                         wget \
                                         dialog \
                                         net-tools \
                                         build-essential