FROM debian:jessie
RUN apt-get update && apt-get install -y tar \
                                         git \
                                         curl \
                                         nano \
                                         wget \
                                         dialog \
                                         net-tools \
                                         build-essential